spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_tools
    username: tools_user
    password: tools_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-status-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.ecommerce.tools.dto"

server:
  port: 8080
